apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-app
spec:
  selector:
    matchLabels:
      run: stress-app
  replicas: 4
  template:
    metadata:
      labels:
        run: stress-app
    spec:
      containers:
      - name: stress-app
        image: quinont/cpulimiteimporta:3
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: stress-app
  labels:
    run: stress-app
spec:
  ports:
  - port: 80
  selector:
    run: stress-app
